name = 'Bitcoin Chatt'
license = 'MIT'
licenselink = 'https://github.com/BitcoinChatt/BitcoinChatt.github.io/blob/main/themes/main/LICENSE'
description = 'Custom theme for the Bitcoin Chattanooga website'
homepage = 'https://github.com/BitcoinChatt/BitcoinChatt.github.io'
demosite = 'https://www.bitcoinchatt.com/'

[author]
  name = 'Jason Sellers / Bitcoin Chatt'
  homepage = 'https://www.bitcoinchatt.com/'